blank_issues_enabled: false
contact_links:
  - name: Question
    url: https://github.com/2214962083/segi-helper-browser-extensions/discussions/new?category=Q-A
    about: 提问或讨论关于 segi-helper-browser-extensions
  - name: Ideas
    url: https://github.com/2214962083/segi-helper-browser-extensions/discussions/new?category=Ideas
    about: 开始讨论改进 segi-helper-browser-extensions
