name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: macOS-latest
    env:
      NODE_OPTIONS: '--max_old_space_size=4096'

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install Pnpm
        uses: pnpm/action-setup@v2.2.1

      - name: Use Node.js v16
        uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
          cache: pnpm

      - name: Install Dependencies
        run: pnpm i

      - name: Build And Pack All
        run: pnpm run pack:all

      - name: Generate Release Note
        run: npx conventional-changelog -p angular -i RELEASE-NOTE.md -s -r 2

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          body_path: RELEASE-NOTE.md
          files: |
            extension/extension.*
